/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.crystals.gradle.docker

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'ru.crystals.gradle.docker.greeting' plugin.
 */
class GradleDockerPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("ru.crystals.gradle.docker.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
