/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.1.0/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    id("com.gradle.plugin-publish") version "2.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    
    // JUnit Jupiter dependencies
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.10.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

group = "io.github.igor-filipenko"
version = "0.0.2"

publishing {
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
}

gradlePlugin {
    website = "https://github.com/igor-filipenko/gradle-docker"
    vcsUrl = "https://github.com/igor-filipenko/gradle-docker.git"

    // Define the plugin
    val docker by plugins.creating {
        id = "io.github.igor-filipenko.docker"
        displayName = "Gradle Docker plugin"
        description = "Gradle plugin for Docker"
        tags = listOf("docker")
        implementationClass = "io.github.igor_filipenko.gradle.docker.GradleDockerPlugin"
    }
}

// Add a source set for the functional test suite
val functionalTestSourceSet = sourceSets.create("functionalTest") {
}

configurations["functionalTestImplementation"].extendsFrom(configurations["testImplementation"])
configurations["functionalTestRuntimeOnly"].extendsFrom(configurations["testRuntimeOnly"])

// Add main source set as dependency for functional tests
dependencies {
    "functionalTestImplementation"(sourceSets["main"].output)
}

// Add a task to run the functional tests
val functionalTest by tasks.registering(Test::class) {
    testClassesDirs = functionalTestSourceSet.output.classesDirs
    classpath = functionalTestSourceSet.runtimeClasspath
    useJUnitPlatform()
}

gradlePlugin.testSourceSets.add(functionalTestSourceSet)

tasks.named<Task>("check") {
    // Run the functional tests as part of `check`
    dependsOn(functionalTest)
}

tasks.named<Test>("test") {
    // Use JUnit Jupiter for unit tests.
    useJUnitPlatform()
}

